dataset:
    countpath: "/home/ubuntu/Programs/Decoders/data/counts.txt"
    datapath: "/home/ubuntu/Programs/Decoders/data/data.txt"
    linecount: 9756039
    vocab: 100000
    window: 128

loader:
    batch_size: 32

embedding:
    device: "cuda:0"
    size: 100000
    dim: 384

decoder:
    device: "cuda:0"
    d_out: 100000
    n_layers: 6 
    n_heads: 6
    d_in: 384 

optimizer:
    lr: 0.01

scheduler:
    base_lr: 0.0001
    max_lr: 0.01

epochs: 1

checkpoint: "/home/akshat/Programs/Decoders/confs/checkpoint.pt"
