checkpoint: 'data/checkpoints'
epochs: 10

window_size: &window_size 64 
vocab_size: &vocab_size 1065
device: &device 'cuda:0'
pad: &pad 1063

train_data:
    datapath: 'data/model/train.txt'
    window_size: *window_size
    vocab_size: *vocab_size
    pad: *pad

dev_data:
    datapath: 'data/model/dev.txt'
    window_size: *window_size
    vocab_size: *vocab_size
    pad: *pad

model:
    vocab_size: *vocab_size
    seq_size: *window_size
    n_layers: 1
    d_emb: 768
    d_k: 64
    d_v: 64
    d_h: 3072
    n_heads: 6
    dropout: 0.1
    device: *device

opt:
    lr: 0.001

sch:
    T_max: 1000

trainer:
    device: *device

train_subset:
    size: 100

dev_subset:
    size: 10

loader:
    drop_last: True
    batch_size: 8
