dataset:
    countpath: "/home/akshat/Programs/Decoders/data/counts.txt"
    datapath: "/home/akshat/Programs/Decoders/data/data.txt"
    linecount: 22780
    vocab: 1000
    window: 32

loader:
    batch_size: 128

decoder:
    device: "cpu"
    d_out: 1000 
    n_layers: 2 
    n_heads: 2
    d_in: 64

optimizer:
    lr: 0.01

scheduler:
    base_lr: 0.00001
    max_lr: 0.001

epochs: 2

checkpoint: "/home/akshat/Programs/Decoders/confs/checkpoint.pt"
