dataset:
    vpath: "/home/akshat/Programs/Decoders/data/counts.txt"
    dpath: "/home/akshat/Programs/Decoders/data/small.txt"
    size: 20000
    limit: 128

embedding:
    dim: 384

model:
    n_layers: 6 
    n_heads: 6
    dim: 384 

train:
    base_lr: 0.0001
    batch_size: 32
    max_lr: 0.01
    epochs: 1

checkpoint: "/home/akshat/Programs/Decoders/confs/checkpoint.pt"
