dataset:
    countpath: "/home/akshat/Programs/Decoders/data/counts.txt"
    datapath: "/home/akshat/Programs/Decoders/data/data.txt"
    linecount: 500
    vocab: 1000
    window: 128

model:
    v: 1000
    w: 128
    d: 6 
    dk: 32
    n_heads: 2
    hidden: 256
    n_blocks: 2
    dropout: 0.1
    device: 'cpu'

loader:
    batch_size: 16

optimizer:
    lr: 0.00025
    weight_decay: 0.01

scheduler:
    T_max: 0.00025

epochs: 5

checkpoint: "/home/akshat/Programs/Decoders/checkpoints"
