dataset:
    countpath: "/home/akshat/Programs/Decoders/data/counts.txt"
    datapath: "/home/akshat/Programs/Decoders/data/data.txt"
    linecount: 5832
    vocab: 1000
    window: 128

loader:
    batch_size: 8 
