window_size: &window_size 128
vocab_size: &vocab_size 56729
device: &device 'cuda:0'


tokenizer: 
    path: "/home/apgpu/Programs/Decoders/checkpoints/tokenizer.pickle"

train_data:
    datapath: '/home/apgpu/Programs/Decoders/data/train.txt'
    window_size: *window_size
    vocab_size: *vocab_size
    pad: 56728

val_data:
    datapath: '/home/apgpu/Programs/Decoders/data/val.txt'
    window_size: *window_size
    vocab_size: *vocab_size
    pad: 56728

loader:
    drop_last: True
    batch_size: 16

model:
    vocab_size: *vocab_size
    embedding_size: 768
    window_size: *window_size
    d_k: 64
    d_v: 64
    n_heads: 6
    hidden: 3072
    n_blocks: 6
    dropout: 0.1
    device: *device

optimizer:
    lr: 0.00001
    weight_decay: 0.01

scheduler:
    T_max: 282

epochs: 1

checkpoint: "/home/apgpu/Programs/Decoders/checkpoints"
