dataset:
    countpath: "/home/apgpu/Programs/Decoders/data/counts.txt"
    datapath: "/home/apgpu/Programs/Decoders/data/data.txt"
    linecount: 3834456
    vocab: 40000
    window: 128

model:
    v: 40000
    d: 384
    dk: 128
    n_heads: 3
    hidden: 1536
    n_blocks: 3
    device: 'cuda:0'

loader:
    batch_size: 32

optimizer:
    lr: 0.01

scheduler:
    base_lr: 0.001
    max_lr: 0.1

epochs: 1

checkpoint: "/home/apgpu/Programs/Decoders/checkpoints"
