checkpoint: "checkpoints"
logdir: "checkpoints/logs"
epochs: 10

window_size: &window_size 64
vocab_size: &vocab_size 1143
device: &device 'cpu'
pad: &pad 1141

tokenizer: 
    path: "/home/akshat/Programs/Decoders/checkpoints/tokenizer"

train_data:
    datapath: '/home/akshat/Programs/Decoders/data/train.txt'
    window_size: *window_size
    vocab_size: *vocab_size
    pad: *pad

dev_data:
    datapath: '/home/akshat/Programs/Decoders/data/dev.txt'
    window_size: *window_size
    vocab_size: *vocab_size
    pad: *pad

train_subset:
    size: 1000

dev_subset:
    size: 500

loader:
    drop_last: True
    batch_size: 64

model:
    vocab_size: *vocab_size
    embedding_size: 128
    window_size: *window_size
    d_k: 64
    d_v: 64
    n_heads: 2
    hidden: 256
    n_blocks: 2
    dropout: 0.1
    device: *device

optimizer:
    lr: 0.0001
    weight_decay: 0.01

scheduler:
    T_max: 1000
