window_size: &window_size 16
vocab_size: &vocab_size 4614
device: &device 'cpu'


tokenizer: 
    path: "/home/akshat/Programs/Decoders/checkpoints/tokenizer.pickle"

dataset:
    datapath: '/home/akshat/Programs/Decoders/data/data.txt'
    linecount: 2694069

collator:
    window_size: *window_size
    vocab_size: *vocab_size
    device: *device

loader:
    drop_last: True
    batch_size: 8 
    shuffle: True 

model:
    vocab_size: *vocab_size
    embedding_size: 32
    window_size: *window_size
    d_k: 16
    d_v: 16
    n_heads: 2
    hidden: 128
    n_blocks: 1
    device: *device

optimizer:
    lr: 0.001
    weight_decay: 0.01

scheduler:
    T_max: 1

epochs: 1

checkpoint: "/home/akshat/Programs/Decoders/checkpoints"

