checkpoint: "checkpoints"
logdir: "checkpoints/logs"
epochs: 20

window_size: &window_size 32 
vocab_size: &vocab_size 1064
device: &device 'cpu'
pad: &pad 1062

tokenizer: 
    path: "/home/apgpu/Programs/Decoders/checkpoints/tokenizer"

train_data:
    datapath: '/home/apgpu/Programs/Decoders/data/model/train.txt'
    window_size: *window_size
    vocab_size: *vocab_size
    pad: *pad

dev_data:
    datapath: '/home/apgpu/Programs/Decoders/data/model/dev.txt'
    window_size: *window_size
    vocab_size: *vocab_size
    pad: *pad

train_subset:
    size: 100

dev_subset:
    size: 10

loader:
    drop_last: True
    batch_size: 8 

model:
    vocab_size: *vocab_size
    seq_size: *window_size
    d_emb: 512
    d_k: 512
    d_v: 512
    d_h: 3072
