tokenizer:
    countpath: "/home/apgpu/Programs/Decoders/data/counts.txt"
    start: "<START>"
    unk: "<UNK>"
    pad: "<PAD>"
    end: "<END>"
    vocab: 40000
    window: 128

dataset:
    #datapath: "/home/apgpu/Programs/Decoders/data/data.txt"
    datapath: "/home/apgpu/Programs/Decoders/data/small.txt"
    #linecount: 3834456
    linecount: 100000

loader:
    drop_last: True
    batch_size: 32
    shuffle: True

model:
    v: 40000
    w: 128
    d: 768 
    dk: 128
    n_heads: 6
    hidden: 3072
    n_blocks: 6
    dropout: 0.1
    device: 'cuda:0'

optimizer:
    #lr: 0.00025
    lr: 0.001
    weight_decay: 0.01

scheduler:
    T_max: 10

epochs: 10

checkpoint: "/home/apgpu/Programs/Decoders/checkpoints"
