tokenizer:
    countpath: "/home/apgpu/Programs/Decoders/data/counts.txt"
    start: "<START>"
    unk: "<UNK>"
    pad: "<PAD>"
    end: "<END>"
    vocab: 40000
    window: 128

dataset:
    datapath: "/home/apgpu/Programs/Decoders/data/data.txt"
    linecount: 3834456

loader:
    drop_last: True
    batch_size: 32
    shuffle: True

model:
    v: 40000
    w: 128
    d: 384
    dk: 128
    n_heads: 3
    hidden: 1536
    n_blocks: 3
    dropout: 0.1
    device: 'cuda:0'

optimizer:
    lr: 0.00025
    weight_decay: 0.01

scheduler:
    T_max: 0.00025

epochs: 1

checkpoint: "/home/apgpu/Programs/Decoders/checkpoints"
